
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MakeMyTrip;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        TestCases tests = new TestCases(); // Initialize your test class

        //TODO: call your test case functions one after other here
        int count=0;

        if(tests.testCase01()){
            System.out.println("Test Case No 1: Passed");
            count++;
        }
        if(tests.testCase02()){
            System.out.println("Test Case No 2: Passed");
            count++;
        }
          if(tests.testCase03()){
            System.out.println("Test Case No 3: Passed");
            count++;
        }
          if(tests.testCase04()){
            System.out.println("Test Case No 4: Passed");
            count++;
        }
         
        System.out.println("Total No of Case passed "+count);
        //END Tests


        tests.endTest(); // End your test by clearning connections and closing browser
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
